### ISSUE TITLE
Issue when exporting work items

### ISSUE THREAD

**Issue by hasithamgh** [solidify/vsts-task-tokenize-in-archive#7]
I'm trying to export multiple work items from JIRA and when I execute the export tool I recive following issue. I was only able to export one work item from JIRA.
![image](https://user-images.githubusercontent.com/12080391/57219394-93ee4180-7015-11e9-863b-54a04f7958bf.png)

[D][15:38:12]    Mapped value 'Committed' to field 'System.State'.
[D][15:38:12]    Exported as type 'Product Backlog Item'.
[E][15:38:12] Unexpected migration error.
[Newtonsoft.Json.JsonException] Newtonsoft.Json.JsonException: Unexpected end while parsing path.
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List`1 filters, Int32 currentPartStartIndex, Boolean query)
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()
   at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)
   at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh):
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List`1 filters, Int32 currentPartStartIndex, Boolean query)
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()
   at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)
   at Newtonsoft.Json.Linq.JToken.SelectToken(String path, Boolean errorWhenNoMatch)
   at Migration.Common.JsonExtensions.ExValue[T](JToken token, String path)
   at JiraExport.JiraItem.get_EpicParent()
   at JiraExport.JiraProvider.<EnumerateIssues>d__21.MoveNext()
   at JiraExport.JiraCommandLine.ExecuteMigration(CommandOption user, CommandOption password, CommandOption url, CommandOption configFile, Boolean forceFresh)
[I][15:38:12] Export complete. Exported 49 items (1 errors, 1 warnings) in 00:00:06.

appreciate your inputs on this issue.

thanks,
Hasitha

**Comment by MOlausson** [comment]
This one was posted in the wrong repo. closing since it's reported in the jira migration tool as well.
