### ISSUE TITLE
Quantifier error

### ISSUE THREAD

**Issue by InitusJames** [solidify/vsts-task-tokenize-in-archive#8]
##[error]System.ArgumentException: parsing "*.json" - Quantifier {x,y} following nothing.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at System.Management.Automation.ParserOps.NewRegex(String patternString, RegexOptions options)
   at System.Management.Automation.ParserOps.MatchOperator(ExecutionContext context, IScriptExtent errorPosition, Object lval, Object rval, Boolean notMatch, Boolean ignoreCase)
   at System.Management.Automation.Interpreter.FuncCallInstruction`7.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**Comment by cedricfortin** [comment]
I came across the exact same error, simply omit the * character, just type .json
